### ISSUE TITLE
[MOD REQUEST] Velonia

### ISSUE THREAD

**Issue by Lierrmm** [ohhsodead/NeoModsX#40]
- Name: Velonia
- Category: Modern Warfare 3
- System Type: XBOX
- Author: Liam
- Version: 1.0.1
- Description: Off host cheat for MW2, MW3 and Ghosts.
- Links: https://github.com/Lierrmm/velonia
- ----------------------- 

Also for MW2 and Ghosts.
- *Please include any other additional information we may need here.

**Comment by ohhsodead** [comment]
> 
> 
>     * Name: Velonia
> 
>     * Category: Modern Warfare 3
> 
>     * System Type: XBOX
> 
>     * Author: Liam
> 
>     * Version: 1.0.1
> 
>     * Description: Off host cheat for MW2, MW3 and Ghosts.
> 
>     * Links: https://github.com/Lierrmm/velonia
> 
> 
> Also for MW2 and Ghosts.
> 
>     * *Please include any other additional information we may need here.

Hi, thanks for requesting your own mod! Do you have any compiled links for the file(s), not all that familiar with xbox mods or even building C++ projects. If you could provide a direct link to the mods then I can have it added soon as. Thanks.

**Comment by Lierrmm** [comment]
I have added a release here: https://github.com/Lierrmm/Velonia/releases/tag/1.0.1 

The format is XEX which is what is compatible with Xbox 360.

**Comment by ohhsodead** [comment]
> 
> 
> I have added a release here: https://github.com/Lierrmm/Velonia/releases/tag/1.0.1
> 
> The format is XEX which is what is compatible with Xbox 360.

@Lierrmm thanks man, exactly what I was looking for! I appreciate your work.

**Comment by ohhsodead** [comment]
@Lierrmm thanks for the contribution bro, now has been added and will be available in the next update release. Please let me know of any mods you create in the future or others you would like to be added too, we lacking xbox mods atm. Also can't find many xbox modders for beta testing the tool :(
