### ISSUE TITLE
[MOD REPORT] Increased Damage, Wall Hack, UAV and more (ID#115) (PS3)

### ISSUE THREAD

**Issue by goldug** [ohhsodead/NeoModsX#41]
- Console Type: PlayStation 3
- Category: Battlefield 3
- Name: Increased Damage, Wall Hack, UAV and more (ID#115)
- System Type: DEX
- Mod Type: EBOOT
- Author: Luckeyy
- Version: 1.0
- Region: ALL
----------------------- 
The mod doesn't do anything. If there's something special you need to do, like a button combination or something, that should be included in the instructions, but there's nothing.

**Comment by goldug** [comment]
I came across one site that claims it's EU version only. I've only tried it on US version.

**Comment by ohhsodead** [comment]
@goldug thanks report man. I'll see what other info I can find for this, maybe there are different versions too.

Note to self, this is for EU region only as found out from OP.

**Comment by ohhsodead** [comment]
updated, thanks man!
