### ISSUE TITLE
[MOD REPORT] Mini Menu (ID#95) (PS3)

### ISSUE THREAD

**Issue by goldug** [ohhsodead/NeoModsX#42]
- Console Type: PlayStation 3
- Category: Red Dead Redemption: GOTYE
- Name: Mini Menu (ID#95)
- System Type: DEX
- Mod Type: EBOOT/SPRX
- Author: RouletteBoi
- Version: 1.1
- Region: ALL
----------------------- 
Game region is not ALL, it's just BLES01294 according to the information ;)

**Comment by ohhsodead** [comment]
thanks, didnt notice this lmao - updated now
