### ISSUE TITLE
[MOD REPORT] Default Game File (ID#114) (PS3)

### ISSUE THREAD

**Issue by goldug** [ohhsodead/NeoModsX#43]
- Console Type: PlayStation 3
- Category: Battlefield 3
- Name: Default Game File (ID#114)
- System Type: DEX
- Mod Type: EBOOT
- Author: Luckeyy
- Version: 1.0
- Region: ALL
----------------------- 
Only for region BLES01275.

**Comment by ohhsodead** [comment]
Fixed.
