### ISSUE TITLE
Sonic Unleashed almost 100% save file.

### ISSUE THREAD

**Issue by megagheims** [ohhsodead/NeoModsX#70]
### What platform is the mod for?

Xbox 360

### Mod Name

Almost 100% save file

### Game/Category

Sonic Unleashed

### Creator

XPG Darkside

### Description

Story mode done ALMOST 100%

Max coins

Sonic stats max

Werehog stats max

Most of the sun/night medals

Most of the souvenirs and video tapes

All day time and night time levels

### System Type (PS3)

- [ ] CEX
- [ ] DEX
- [ ] HEN
- [ ] ALL

### Game Regions

ALL

### Source/Links

https://www.xpgamesaves.com/threads/sonic-unleashed-xbox-360-100-complete-save-request.66512/
scroll a bit and you'll find a download button.
if not, there's the download link:
https://mega.nz/#!QAoVxQKR!GJNVfBZXjKE073i-fPSeSRdKcUFZ-o9JAjmrBnsRMOU

**Comment by ohhsodead** [comment]
Added.
