### ISSUE TITLE
El Host

### ISSUE THREAD

**Issue by Baptic** [ohhsodead/NeoModsX#71]
**Mod Details**
- Platform: XBOX360
- Game/Category: MW3
- Name: El Host
- Creator: Im Crout

**Sources Links:**
https://www.mediafire.com/file/yzv76b4gtah3vxn/El_Host_Public_Release_1.0.rar/file

**Additional Details**
 Demo vid - https://www.youtube.com/watch?v=3ceUV_KqtFs

**Comment by ohhsodead** [comment]
Added to database.
